// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IMDB.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MoviesFeature : object, Xunit.IClassFixture<MoviesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Movies.feature"
#line hidden
        
        public MoviesFeature(MoviesFeature.FixtureData fixtureData, IMDB_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Movies", "\t\t In order to perform operations on movies", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Movies List is not Empty")]
        [Xunit.TraitAttribute("FeatureTitle", "Movies")]
        [Xunit.TraitAttribute("Description", "Movies List is not Empty")]
        [Xunit.TraitAttribute("Category", "listMovies")]
        public virtual void MoviesListIsNotEmpty()
        {
            string[] tagsOfScenario = new string[] {
                    "listMovies"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Movies List is not Empty", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("I want to see the movies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "year",
                            "plot",
                            "actorIDs",
                            "producerID"});
                table1.AddRow(new string[] {
                            "movie1",
                            "2000",
                            "movie1 plot",
                            "1",
                            "1"});
                table1.AddRow(new string[] {
                            "movie2",
                            "1998",
                            "Movie2 plot",
                            "1",
                            "1"});
#line 7
 testRunner.Then("List of movies should be like", ((string)(null)), table1, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Movies List is Empty")]
        [Xunit.TraitAttribute("FeatureTitle", "Movies")]
        [Xunit.TraitAttribute("Description", "Movies List is Empty")]
        public virtual void MoviesListIsEmpty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Movies List is Empty", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 13
 testRunner.Given("I want to see the movies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "year",
                            "plot",
                            "actorIDs",
                            "producerID"});
#line 14
 testRunner.Then("List of movies should be like", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="user adds movie with valid data")]
        [Xunit.TraitAttribute("FeatureTitle", "Movies")]
        [Xunit.TraitAttribute("Description", "user adds movie with valid data")]
        [Xunit.TraitAttribute("Category", "addMovie")]
        [Xunit.InlineDataAttribute("testName", "2000", "This is a test plot", "1,2", "1", new string[0])]
        [Xunit.InlineDataAttribute("testName", "2000", "This is a test plot", "1", "1", new string[0])]
        public virtual void UserAddsMovieWithValidData(string name, string year, string plot, string actors, string producer, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("year", year);
            argumentsOfScenario.Add("plot", plot);
            argumentsOfScenario.Add("actors", actors);
            argumentsOfScenario.Add("producer", producer);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user adds movie with valid data", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
 testRunner.Given(string.Format("the inputs are Name: \'{0}\' Year: \'{1}\' Plot: \'{2}\' Actors: \'{3}\' and Producer: \'{" +
                            "4}\'", name, year, plot, actors, producer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
 testRunner.When("I add the movie", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "year",
                            "plot",
                            "actorIDs",
                            "producerID"});
                table3.AddRow(new string[] {
                            "movie1",
                            "2000",
                            "movie1 plot",
                            "1",
                            "1"});
                table3.AddRow(new string[] {
                            "movie2",
                            "1998",
                            "Movie2 plot",
                            "1",
                            "1"});
                table3.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", year),
                            string.Format("{0}", plot),
                            string.Format("{0}", actors),
                            string.Format("{0}", producer)});
#line 21
 testRunner.Then("List of movies should be like", ((string)(null)), table3, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="user adds an existing movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movies")]
        [Xunit.TraitAttribute("Description", "user adds an existing movie")]
        [Xunit.TraitAttribute("Category", "addMovie")]
        [Xunit.InlineDataAttribute("movie1", "2000", "movie1 plot", "1", "1", new string[0])]
        public virtual void UserAddsAnExistingMovie(string name, string year, string plot, string actors, string producer, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("year", year);
            argumentsOfScenario.Add("plot", plot);
            argumentsOfScenario.Add("actors", actors);
            argumentsOfScenario.Add("producer", producer);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user adds an existing movie", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
 testRunner.Given(string.Format("the inputs are Name: \'{0}\' Year: \'{1}\' Plot: \'{2}\' Actors: \'{3}\' and Producer: \'{" +
                            "4}\'", name, year, plot, actors, producer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
 testRunner.When("I add the movie", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "year",
                            "plot",
                            "actorIDs",
                            "producerID"});
                table4.AddRow(new string[] {
                            "movie1",
                            "2000",
                            "movie1 plot",
                            "1",
                            "1"});
                table4.AddRow(new string[] {
                            "movie2",
                            "1998",
                            "Movie2 plot",
                            "1",
                            "1"});
#line 35
 testRunner.Then("List of movies should be like", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="user adds a movie with invalid data")]
        [Xunit.TraitAttribute("FeatureTitle", "Movies")]
        [Xunit.TraitAttribute("Description", "user adds a movie with invalid data")]
        [Xunit.TraitAttribute("Category", "addMovie")]
        [Xunit.InlineDataAttribute("testName", "2000", "", "1", "1", new string[0])]
        [Xunit.InlineDataAttribute("", "2000", "testPlot", "1", "1", new string[0])]
        [Xunit.InlineDataAttribute("", "2000", "", "1", "1", new string[0])]
        [Xunit.InlineDataAttribute("testName", "1", "testPlot", "1", "1", new string[0])]
        [Xunit.InlineDataAttribute("testName", "2000", "testPlot", "-1", "1", new string[0])]
        [Xunit.InlineDataAttribute("testName", "2000", "testPlot", "1", "-1", new string[0])]
        public virtual void UserAddsAMovieWithInvalidData(string name, string year, string plot, string actors, string producer, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("year", year);
            argumentsOfScenario.Add("plot", plot);
            argumentsOfScenario.Add("actors", actors);
            argumentsOfScenario.Add("producer", producer);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user adds a movie with invalid data", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 45
 testRunner.Given(string.Format("the inputs are Name: \'{0}\' Year: \'{1}\' Plot: \'{2}\' Actors: \'{3}\' and Producer: \'{" +
                            "4}\'", name, year, plot, actors, producer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 46
 testRunner.When("I add the movie", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 47
 testRunner.Then("I should have an error \"Invalid arguments\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "year",
                            "plot",
                            "actorIDs",
                            "producerID"});
                table5.AddRow(new string[] {
                            "movie1",
                            "2000",
                            "movie1 plot",
                            "1",
                            "1"});
                table5.AddRow(new string[] {
                            "movie2",
                            "1998",
                            "Movie2 plot",
                            "1",
                            "1"});
#line 48
 testRunner.And("List of movies should be like", ((string)(null)), table5, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MoviesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MoviesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
